

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "MainPage.xaml.h"




void ::Cisco_Password_Decrypter::MainPage::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///MainPage.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the Button named 'buttonDecrypt'
    buttonDecrypt = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"buttonDecrypt"));
    // Get the TextBox named 'textboxOutputPassword'
    textboxOutputPassword = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"textboxOutputPassword"));
    // Get the TextBox named 'textboxInputHash'
    textboxInputHash = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"textboxInputHash"));
}

void ::Cisco_Password_Decrypter::MainPage::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Cisco_Password_Decrypter::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::buttonDecrypt_Click);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(target))->TextChanged +=
            ref new ::Windows::UI::Xaml::Controls::TextChangedEventHandler(this, (void (::Cisco_Password_Decrypter::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Controls::TextChangedEventArgs^))&MainPage::textboxOutputPassword_TextChanged);
        break;
    case 3:
        (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(target))->TextChanged +=
            ref new ::Windows::UI::Xaml::Controls::TextChangedEventHandler(this, (void (::Cisco_Password_Decrypter::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Controls::TextChangedEventArgs^))&MainPage::textboxInputHash_TextChanged);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

